language: go

go:
- 1.9

branches:
  only:
  - master
  - /^v.*$/

install:
- go get -u github.com/golang/dep/cmd/dep

script:
- make deps
- make test
- make build


before_deploy:
- make release

deploy:
  provider: releases
  api_key:
    secure: 
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
